spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  minio:
    url: http://127.0.0.1:9000/
    access-key: minioadmin
    secret-key: minioadmin
    bucket: minio
    create-bucket: true

#server:
#  compression:
#    enabled: true
#  servlet:
#    context-path: /api
#  port: 443
#  ssl:
#    key-store: classpath:404z.cn.jks
#    key-store-password: ChengKai1998!
#    key-store-type: JKS

logging:
  file:
    name: /log/demo-minio.log
