spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://192.168.18.248:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: risecomm
    password: Risecomm2021!
  redis:
    database: 0
    host: 192.168.18.248
    port: 6379
    password: Risecomm2021!
    timeout: 10s

sa-token:
  is-log: true

logging:
  level:
    root: info
    com.demo.mapper: trace
