spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB

#server:
#  compression:
#    enabled: true
#  servlet:
#    context-path: /api
#  port: 443
#  ssl:
#    key-store: classpath:404z.cn.jks
#    key-store-password: ChengKai1998!
#    key-store-type: JKS

logging:
  file:
    name: /log/demo-util.log

id:
  machine-id: 0
  machine-bits: 8
  sequence-bits: 12

ip2region:
  resource-path: /file/ip2region/ip2region.zxdb
