spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
#server:
#  servlet:
#    context-path: /api
#  port: 443
#  ssl:
#    key-store: classpath:k3t3.com.pfx
#    key-store-password: 40I69DfH
#    key-store-type: PKCS12
logging:
  file:
    name: /log/demo-springboot.log
